receivers:
  otlp:
    protocols:
      http:
      grpc:

exporters:
  debug: {}   
  prometheus:
    endpoint: 0.0.0.0:9464

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]